## Basic Configuration

baseurl = "https://elfredpagan.com/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Elfred Pagán"
title = "Elfred Pagán"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Elfred Pagán"
intro = "Engineer/Amateur Cook"
description = "Hey y'all, I'm Elfred, software engineer and amateur cook living in austin TX. I mostly write iOS apps"
authorimage = "profile.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Personal site"
keywords = "developer"

## Social Accounts
[params.social]
github = "elfredpagan"
instagram = "elfredpagan"
linkedin = "elfred"
twitter = "elfredpagan"
stackoverflow = "12636/elfred"
email = "elfred@elfredpagan.com"

## Extras
[params.extra]
copyright = "© 2017. Elfred Pagán. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
# [[menu.main]]
#     name = "coderag"
#     identifier = "coderag"
#     weight = 300
#     url = "/coderag/"
